# Generated by Django 3.2.3 on 2021-05-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.TextField(default='news_object', max_length='100')),
                ('title', models.TextField(default='News Title')),
                ('short_summary', models.TextField(default='This is news short summary')),
                ('deatils', models.TextField(default='News deatils')),
                ('write', models.TextField(default='write name')),
                ('date', models.TextField(default='date')),
            ],
        ),
    ]
