# Generated by Django 3.2.3 on 2021-06-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='write',
            new_name='writer',
        ),
    ]
