# Generated by Django 3.2.3 on 2021-05-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='TitleModel',
        ),
        migrations.RenameField(
            model_name='titlemodel',
            old_name='about',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='titlemodel',
            old_name='name',
            new_name='title',
        ),
    ]
