# Generated by Django 3.2.3 on 2021-05-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210524_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb', models.TextField(default='https://facebook.com')),
                ('tw', models.TextField(default='https://youtube.com')),
                ('yt', models.TextField(default='https://twitter.com')),
            ],
        ),
    ]
