# Generated by Django 3.2.3 on 2021-05-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_socialmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='fb',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='tw',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='yt',
            new_name='youtube',
        ),
    ]
