# Generated by Django 3.2.3 on 2021-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210524_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.TextField(default='')),
                ('title', models.TextField()),
                ('desc', models.TextField(default='.')),
                ('facebook', models.TextField(default='https://facebook.com')),
                ('twitter', models.TextField(default='https://youtube.com')),
                ('youtube', models.TextField(default='https://twitter.com')),
                ('footer_credit', models.TextField(default='All right reserver by MegNews')),
                ('mobile', models.TextField(default='+8801234567890')),
            ],
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='TitleModel',
        ),
    ]
