# Generated by Django 3.2.3 on 2021-05-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210524_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearence',
            name='facebook',
            field=models.CharField(default='https://facebook.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='appearence',
            name='footer_credit',
            field=models.TextField(default='All right reserver by MegNews', max_length=100),
        ),
        migrations.AlterField(
            model_name='appearence',
            name='mobile',
            field=models.CharField(default='+8801234567890', max_length=100),
        ),
        migrations.AlterField(
            model_name='appearence',
            name='obj_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appearence',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appearence',
            name='twitter',
            field=models.CharField(default='https://youtube.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='appearence',
            name='youtube',
            field=models.CharField(default='https://twitter.com', max_length=100),
        ),
    ]
